"""initial_schema

Revision ID: 91728b8baa9a
Revises: 
Create Date: 2026-10-01 23:14:37.583459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91728b8baa9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_categories_slug', 'categories', ['slug'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_groups_category'), 'groups', ['category'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('mentors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('college', sa.String(length=255), nullable=False),
    sa.Column('experience', sa.String(length=100), nullable=False),
    sa.Column('badge', sa.String(length=100), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('topics', sa.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('sessions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('avatar_initials', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED', name='connection_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'receiver_id', name='uq_connections_requester_receiver')
    )
    op.create_index('idx_connections_receiver', 'connections', ['receiver_id'], unique=False)
    op.create_index('idx_connections_status', 'connections', ['status'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_receiver_id'), 'connections', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_connections_requester_id'), 'connections', ['requester_id'], unique=False)
    op.create_index(op.f('ix_connections_status'), 'connections', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_devices_user_active', 'devices', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_token'), 'devices', ['token'], unique=True)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('group_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_membership_group_user')
    )
    op.create_index('idx_group_memberships_user', 'group_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_id'), 'group_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_group_memberships_user_id'), 'group_memberships', ['user_id'], unique=False)
    op.create_table('mentor_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='mentor_request_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mentor_id', 'user_id', name='uq_mentor_request_mentor_user')
    )
    op.create_index('idx_mentor_requests_user', 'mentor_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_mentor_requests_id'), 'mentor_requests', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_requests_mentor_id'), 'mentor_requests', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentor_requests_user_id'), 'mentor_requests', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('connection', 'like', 'comment', 'opportunity', 'group', 'mentor', 'system', name='notification_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('ONLINE', 'OFFLINE', 'HYBRID', name='opportunity_mode_enum'), nullable=False),
    sa.Column('eligibility', sa.String(length=500), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('prize', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('registration_url', sa.String(length=1024), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'EXPIRED', 'REJECTED', name='opportunity_status_enum'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_opportunity_source_source_id')
    )
    op.create_index('idx_opportunities_deadline_status', 'opportunities', ['deadline', 'status'], unique=False)
    op.create_index('idx_opportunities_domain', 'opportunities', ['domain'], unique=False)
    op.create_index('idx_opportunities_mode', 'opportunities', ['mode'], unique=False)
    op.create_index(op.f('ix_opportunities_category_id'), 'opportunities', ['category_id'], unique=False)
    op.create_index(op.f('ix_opportunities_deadline'), 'opportunities', ['deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_is_active'), 'opportunities', ['is_active'], unique=False)
    op.create_index(op.f('ix_opportunities_is_featured'), 'opportunities', ['is_featured'], unique=False)
    op.create_index(op.f('ix_opportunities_source'), 'opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_opportunities_source_id'), 'opportunities', ['source_id'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('knowledge', 'question', 'project', 'resource', 'opportunity', 'discussion', name='post_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('external_url', sa.String(length=1024), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_author_created', 'posts', ['author_id', 'created_at'], unique=False)
    op.create_index('idx_posts_is_deleted_created', 'posts', ['is_deleted', 'created_at'], unique=False)
    op.create_index('idx_posts_type_created', 'posts', ['type', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_group_id'), 'posts', ['group_id'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_is_deleted'), 'posts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_posts_type'), 'posts', ['type'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'DISMISSED', name='report_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_status_created', 'reports', ['status', 'created_at'], unique=False)
    op.create_index('idx_reports_target', 'reports', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_target_id'), 'reports', ['target_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('college', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('year', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('interests', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_profiles_branch', 'user_profiles', ['branch'], unique=False)
    op.create_index('idx_user_profiles_college', 'user_profiles', ['college'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_post_created', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_is_deleted'), 'comments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_table('post_likes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_like_post_user')
    )
    op.create_index('idx_post_likes_post_id', 'post_likes', ['post_id'], unique=False)
    op.create_index('idx_post_likes_user_id', 'post_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_likes_id'), 'post_likes', ['id'], unique=False)
    op.create_index(op.f('ix_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_likes_user_id'), 'post_likes', ['user_id'], unique=False)
    op.create_table('saved_opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_saved_opportunity_user_opportunity')
    )
    op.create_index('idx_saved_opps_opp_id', 'saved_opportunities', ['opportunity_id'], unique=False)
    op.create_index('idx_saved_opps_user_id', 'saved_opportunities', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_opportunities_id'), 'saved_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_saved_opportunities_opportunity_id'), 'saved_opportunities', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_saved_opportunities_user_id'), 'saved_opportunities', ['user_id'], unique=False)
    op.create_table('saved_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_saved_post_post_user')
    )
    op.create_index('idx_saved_posts_post_id', 'saved_posts', ['post_id'], unique=False)
    op.create_index('idx_saved_posts_user_id', 'saved_posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_posts_id'), 'saved_posts', ['id'], unique=False)
    op.create_index(op.f('ix_saved_posts_post_id'), 'saved_posts', ['post_id'], unique=False)
    op.create_index(op.f('ix_saved_posts_user_id'), 'saved_posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_posts_user_id'), table_name='saved_posts')
    op.drop_index(op.f('ix_saved_posts_post_id'), table_name='saved_posts')
    op.drop_index(op.f('ix_saved_posts_id'), table_name='saved_posts')
    op.drop_index('idx_saved_posts_user_id', table_name='saved_posts')
    op.drop_index('idx_saved_posts_post_id', table_name='saved_posts')
    op.drop_table('saved_posts')
    op.drop_index(op.f('ix_saved_opportunities_user_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_opportunities_opportunity_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_opportunities_id'), table_name='saved_opportunities')
    op.drop_index('idx_saved_opps_user_id', table_name='saved_opportunities')
    op.drop_index('idx_saved_opps_opp_id', table_name='saved_opportunities')
    op.drop_table('saved_opportunities')
    op.drop_index(op.f('ix_post_likes_user_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_post_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_id'), table_name='post_likes')
    op.drop_index('idx_post_likes_user_id', table_name='post_likes')
    op.drop_index('idx_post_likes_post_id', table_name='post_likes')
    op.drop_table('post_likes')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_deleted'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_index('idx_comments_post_created', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index('idx_user_profiles_college', table_name='user_profiles')
    op.drop_index('idx_user_profiles_branch', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_reports_target_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index('idx_reports_target', table_name='reports')
    op.drop_index('idx_reports_status_created', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_posts_type'), table_name='posts')
    op.drop_index(op.f('ix_posts_is_deleted'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_group_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index('idx_posts_type_created', table_name='posts')
    op.drop_index('idx_posts_is_deleted_created', table_name='posts')
    op.drop_index('idx_posts_author_created', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_featured'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_active'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_deadline'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_category_id'), table_name='opportunities')
    op.drop_index('idx_opportunities_mode', table_name='opportunities')
    op.drop_index('idx_opportunities_domain', table_name='opportunities')
    op.drop_index('idx_opportunities_deadline_status', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_mentor_requests_user_id'), table_name='mentor_requests')
    op.drop_index(op.f('ix_mentor_requests_mentor_id'), table_name='mentor_requests')
    op.drop_index(op.f('ix_mentor_requests_id'), table_name='mentor_requests')
    op.drop_index('idx_mentor_requests_user', table_name='mentor_requests')
    op.drop_table('mentor_requests')
    op.drop_index(op.f('ix_group_memberships_user_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_index('idx_group_memberships_user', table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_token'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index('idx_devices_user_active', table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_connections_status'), table_name='connections')
    op.drop_index(op.f('ix_connections_requester_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_receiver_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index('idx_connections_status', table_name='connections')
    op.drop_index('idx_connections_receiver', table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_table('mentors')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_category'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index('idx_categories_slug', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
