// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYCC2GJJx7WK0WNExaURFibQwHGs3b7Cw',
    appId: '1:925004572928:web:f2bff3d40127a833bf2be5',
    messagingSenderId: '925004572928',
    projectId: 'link-up-e0998',
    authDomain: 'link-up-e0998.firebaseapp.com',
    storageBucket: 'link-up-e0998.firebasestorage.app',
    measurementId: 'G-QF7FGKP564',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeN2Z-LSQi_KjTRnhQNLnOrj_RW3SsDEc',
    appId: '1:925004572928:android:fd1c356cda22ba9ebf2be5',
    messagingSenderId: '925004572928',
    projectId: 'link-up-e0998',
    storageBucket: 'link-up-e0998.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqBpIoCs9Opb7jptTcY8FFp-tl46SzLIA',
    appId: '1:925004572928:ios:1271d50b0b73feaebf2be5',
    messagingSenderId: '925004572928',
    projectId: 'link-up-e0998',
    storageBucket: 'link-up-e0998.firebasestorage.app',
    iosClientId: '925004572928-6p149srebf8okbn2uhtcuhtha6kogadi.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqBpIoCs9Opb7jptTcY8FFp-tl46SzLIA',
    appId: '1:925004572928:ios:1271d50b0b73feaebf2be5',
    messagingSenderId: '925004572928',
    projectId: 'link-up-e0998',
    storageBucket: 'link-up-e0998.firebasestorage.app',
    iosClientId: '925004572928-6p149srebf8okbn2uhtcuhtha6kogadi.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYCC2GJJx7WK0WNExaURFibQwHGs3b7Cw',
    appId: '1:925004572928:web:8bd097bd282b2a25bf2be5',
    messagingSenderId: '925004572928',
    projectId: 'link-up-e0998',
    authDomain: 'link-up-e0998.firebaseapp.com',
    storageBucket: 'link-up-e0998.firebasestorage.app',
    measurementId: 'G-2241C37BN6',
  );
}
